name: m2
description: A tool for managing your local Maven repository.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  random_string: ^2.3.1